# Generated by Django 4.0.4 on 2022-06-25 19:51

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(max_length=140, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
