# Generated by Django 4.0.4 on 2022-09-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_newsletter_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Subsrcibers'},
        ),
    ]
